fusion:
  MAX_NUM_WORDS: 15000
  EMBEDDING_DIM: 300
  MAX_SEQ_LENGTH: 140
  REPORT_FIELD: report
  ID_FIELD: id
  ID: id
  TARGET: dm # The header of the dependant variable
  DROP: ["name", "id"]
  EARLY_FUSION: True
  train_embedding: True  # Keep it same as EARLY_FUSION
  DENSE_LAYER: 128
  EPOCHS: 10
  NCLASSES: 1
bert_model:
  MAX_LENGTH: 40
  NCLASSES: 1
  REPORT_FIELD: report
  ID: id
  TARGET: dm
  DROP: ["name", "id"]
train:
  MAX_LENGTH: 40
  NCLASSES: 3
  REPORT_FIELD: report
  ID: id
  TARGET: dm
  DROP: ["name", "id"]
NCLASSES: 1